config/routes.rb
Rails.application.routes.draw do






  root 'home#top'
  get 'home/readme' => 'home#readme'
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
   }
   
   
   resources :users, :only => [:index, :edit, :update]
   post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   get 'reservations/my_reserved' => 'reservations#my_reserved'
   resources :reservations
   resources :user_types
   post 'reservations/confirm' => 'reservations#confirm'
   
   get 'inquiries/:id/answer' => 'inquiries#answer'
   resources :inquiries
   
   get 'answers/:id/new' => 'answers#new'
   resources :answers, :only => [:create, :show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    # before_action :pre_process_params, only:[:confirm,:create]
    before_action :authenticate_user!

    def new
        logger.debug("============================ current_user = #{current_user.name}")
        @reservation = Reservation.new
        # @contents = RequestContent.all
        @date = params[:date]
        @frame = params[:frame]
        logger.debug("============================ @date  = #{@date.to_date.wday}")
        logger.debug("============================ @frame  = #{@frame}")
        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def index
        if current_user
            if User.find(current_user.id).user_type == "1"
                @reservations = Reservation.all
            else 
                @reservations = Reservation.where(user_id: current_user.id)
            end
            # logger.debug("============================----- weekday = #{Global::WEEKDAY[1]}")
        end
    end
    
    # ここから
    
    def my_reserved
        if User.find(current_user.id).user_type == "1"
            @reservations = Reservation.where('reserved_date >= ?', Date.today).order(:reserved_date).order(:reserved_space)
        else 
            @reservations = Reservation.where('user_id = ? and reserved_date >= ?',current_user.id, Date.today).order(:reserved_date).order(:reserved_space)
        end
        @reservations.each do |reservation|
            logger.debug("============================  @reservations = #{reservation.reserved_date}")
        end
    end
    
    def make_holiday
        
        @reservation = Reservation.new(user_id: 0,reserved_date: params[:date],reserved_space: params[:space], remarks: "休み")

        if @reservation.save
            flash[:notice] = "#{params[:date].to_date.strftime("%Y年 %-m月 %-d日")}の#{params[:space]}時〜を休みにしました"
            redirect_to reservations_path
        else
            flash[:notice] = "休み入力できませんでした"
            render "reservations/index"
        end
    end
    
    
    def create
        
        @reservation = Reservation.new(reservation_params)
        @user = User.find(current_user.id)
        
        
        respond_to do |format|
          if @reservation.save
            SampleMailer.send_when_create(@reservation,@user).deliver
            AdminMailer.send_when_reserved(@reservation,@user).deliver
            format.html { redirect_to reservations_path, notice: "#{@reservation.reserved_date.to_date.strftime("%Y年 %-m月 %-d日")}の#{@reservation.reserved_space}時〜予約承りました" }
            format.json { render :index, status: :created, location: @reservation }
          else
            format.html { render :index }
            format.json { render json: @reservation.errors, status: :unprocessable_entity }
          end
        end

        
        #   respond_to do |format|
        #       if @reservation.save
        # 　　　　ReserveMailer.send_when_reserved(@reservation,@user).deliver
        #         format.html { redirect_to @reservation, notice: 'User was successfully created.' }
        #         format.json { render :show, status: :created, location: @reservation }
        #       else
        #         format.html { render :new }
        #         format.json { render json: @reservation.errors, status: :unprocessable_entity }
        #       end
        #   end
    


        # logger.debug("============================create reserve_date  = #{params[:reservation][:reserved_date]}")
        # redirect_to reservations_path
    end
    
    def destroy
        @reservation = Reservation.find(params[:id])
        if @reservation.destroy
            flash[:notice] = "予約を取り消しました"
          redirect_to reservations_my_reserved_path
        else 
          redirect_back(fallback_location: reservations_path)
        end
    end
    
    private
        
        def reservation_params
            params.require(:reservation).permit(:user_id, :reserved_date, :remarks, :reserved_space)
        end
        
        
        def pre_process_params
            params[:reservation][:sex] = params[:reservation][:sex].to_i
            params[:reservation][:section] = params[:reservation][:section].to_i
        end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
    
    def reserved_check(date,frame)
        if Reservation.find_by(reserved_date: date, reserved_space: frame)
            reservation = Reservation.find_by(reserved_date: date, reserved_space: frame)
            return reservation
        end
    end
end

app/views/reservations/_form.html.erb
<div class="modal-dialog modal-lg" style="z-index: 1500">
 <div class="modal-content">
    <div class="container">
        <%= form_for @reservation, :url => {:action => "create" }, :data => {:remote => true} do |f| %>
            <%= render "shared/error_messages", model: @reservation %>
            
            <div class="input-wrapper">
                <div class="label-field">
                    <span>氏名</span>
                </div>
                <div class="input-field">
                    <%= current_user.name %>
                </div>
            </div>
            
  
            
            <div class="input-wrapper">
                <div class="label-field">
                    <span>性別</span>
                </div>
                <div class="input-field">
                    <%= Global::GENDER[current_user.gender] %>
                </div>
            </div>
            
            <div class="input-wrapper">
                <div class="label-field">
                    <span>電話番号</span>
                </div>
                <div class="input-field">
                   <%= current_user.tel %>           
                </div>
            </div>
            
            <div class="input-wrapper">
                <div class="label-field">
                    <span>予約日時</span>
                </div>
                <div class="input-field">
                   <%= @date.to_date.strftime("%Y年 %-m月 %-d日") %>(<%= Global::WEEKDAY[@date.to_date.wday] %>)　<%= @frame %>:00〜        
                </div>
            </div>
            <div class="input-wrapper">
                <div class="label-field">
                    <span>備考</span>
                </div>
                <div class="input-field">
                   <%= f.text_area :remarks %>           
                </div>
            </div>
                <%= f.hidden_field :reserved_date, :value => @date %>
                <%= f.hidden_field :reserved_space, :value => @frame %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <button type="button" class="btn btn-warning" data-dismiss="modal">キャンセル</button>
                <%= button_to "予約を確定", {action: 'create'}, {method: :post, class: "btn btn-primary"} %>
                <!-- 管理者なら休日ボタンを表示 -->
                <% if User.find(current_user.id).user_type == "1"  %>
                  <%= link_to "お休み", "/reservations/make_holiday/#{@date}/#{@frame}", {method: :post, class: "btn btn-danger"} %>
                <% end %>
        <% end %>
    </div>   
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container">
    <h2 class="calendar-title">予約カレンダー</h2>
    
        <table class="table table-bordered table-schedule">
          <thead>
            <tr>
              <th scope="col">#</th>
            <% 13.times do |i| %>
              <th scope="col"><%= i+10 %>時</th>
            <% end %>
             
            </tr>
          </thead>
          <tbody>
            <% d = DateTime.now + 0.375 %>
            <% logger.debug("------------------------------ date = #{d}") %>
            <% 14.times do |i| %>
              <% if i > 0 %>
              <!-- 明日以降  -->
                <tr>
                  <th scope="row"><%= (d+i).strftime("%-m/%d") %>　(<%= Global::WEEKDAY[(d+i).wday.to_i] %>)</th>
                  <% 13.times do |j| %>
                    <% if @reserved = reserved_check((d+i),(j+10)) %>
                      <% if User.find(current_user.id).user_type == "1" && @reserved.user_id != 0 %>
                      <!-- 予約の備考最初の10バイトを切り取る-->
                        <% if @reserved.remarks %>
                         <% remarks = @reserved.remarks[0..13] %>
                        <% else %>
                         <% remarks = "" %>
                        <% end %>
                        <% logger.debug("~~~~~~~~~~~~~~~~~~~ html user_id = #{@reserved.user_id}") %>
                        <% if @reserved.user_id == 0 %>
                          <td style="color: red;" align="center" id="reserved" data-toggle="tooltip" data-html="true" title="<%= User.find(@reserved.user_id).name %><br><%= User.find(@reserved.user_id).tel %><br><%= User.find(@reserved.user_id).introducer %><br><%= remarks %>", data-container="body">==</td>
                        <% else %>
                          <td align="center" id="reserved" data-toggle="tooltip" data-html="true" title="<%= User.find(@reserved.user_id).name %><br><%= User.find(@reserved.user_id).tel %><br><%= User.find(@reserved.user_id).introducer %><br><%= remarks %>", data-container="body">✖️</td>
                        <% end %>
                      <% else %>
                        <% if @reserved.user_id == 0 %>
                          <td style="color: red;" align="center">==</td>
                        <% else %>
                          <td align="center">✖</td>
                        <% end %>
                      <% end %>
                    <% else %>
                      <td align="center"><%= link_to "◎", new_reservation_path(date: (d+i),frame: (j+10)), remote: true, class: "schedule open-modal" %></td>
                      <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
                    <% end %>
                  <% end %>
                </tr>
              <% else %>
              <!-- 今日  -->
                <tr class="today">
                  <th scope="row"><%= (d+i).strftime("%-m/%d") %>　(<%= Global::WEEKDAY[(d+i).wday.to_i] %>)</th>
                  <% 13.times do |j| %>
                    <% if @reserved = reserved_check((d+i),(j+10)) %>
                    <!-- 管理者のみ予約済み内容を吹き出しで表示 -->
  　　　　　　　　　　          <% if User.find(current_user.id).user_type == "1" %>
                      　<td align="center" id="reserved" data-toggle="tooltip" data-html="true" title="<%= User.find(@reserved.user_id).name %><br><%= User.find(@reserved.user_id).tel %>", data-container="body">✖️</td>
                      <% else %>
                        <% if @reserved.user_id == 0 %>
                          <td class="holiday" align="center">︎=</td>
                        <% else %>
                          <td align="center">✖︎</td>
                        <% end %>
                      <% end %>
                    <% else %>
                        <td align="center">◎</td>
                      <% end %>
                    <% end %>
                </tr>              
              <% end %>

             <% end %>
          </tbody>
        </table>
        
     <div id="reserveModal" class="modal" onclick="closeModal(this)">
        <div class="modal-content">
            <span class="close" onclick="closeModal(this)">&times;</span>
            <div id="modal-form"></div>
        </div>
    </div> 
    
</div>

app/views/reservations/my_reserved.html.erb
<div class="container">

    <h2 class="my-reserved-title">予約履歴</h2>
    
        <table class="table table-bordered table-schedule">
          <thead>
            <tr>
              <th scope="col">予約日付</th>
              <th scope="col">時間</th>
              <% if User.find(current_user.id).user_type == "1" %>
               <th scope="col">予約者</th>
               <th scope="col">Action</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @reservations.each do |reservation| %>
               <tr>
                  <td><%= reservation.reserved_date %></td>
                  <td><%= reservation.reserved_space %>:00</td>
                  <% if User.find(current_user.id).user_type == "1" %>
                    <td><%= User.find(reservation.user_id).name %></td>
                    <td><%= link_to "削除", "/reservations/#{reservation.id}", :method => "delete", data: { confirm: "#{reservation.reserved_date}⇨#{reservation.reserved_space}:00の予約を削除しますか？" } %></td>
                  <% end %>
               </tr>
            <% end %>
          </tbody>
        </table>

    
</div>

app/views/reservations/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form') %>")
$("#user-modal").modal("show")

<% if @date.present? %>
    var dateField = document.getElementById("reserved_date");
    dateField.value = '<%= @date %>';
<% end %>
var modal = document.getElementById("reserveModal");
modal.style.display = 'block';


if($('#error_explanation')[0]){
    $(".modal").animate({scrollTop:0});
}