config/routes.rb
Rails.application.routes.draw do






  root 'home#top'
  get 'home/readme' => 'home#readme'
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
   }
   
   
   resources :users, :only => [:index, :edit, :update]
   post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   get 'reservations/my_reserved' => 'reservations#my_reserved'
   resources :reservations
   resources :user_types
   post 'reservations/confirm' => 'reservations#confirm'
   
   get 'inquiries/:id/answer' => 'inquiries#answer'
   resources :inquiries
   
   get 'answers/:id/new' => 'answers#new'
   resources :answers, :only => [:create, :show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  
  def new
    @user_type = UserType.new
  end
  
  def create
    @user_type = UserType.new(user_type_params)
    if @user_type.save
      flash[:notice] = "ユーザータイプを追加しました"
      redirect_to user_types_path      
    else
      flash[:notice] = "ユーザータイプを追加できませんでした"
      render "user_types/new"      
    end
  end
  
  def index
    @user_types = UserType.all
  end
  
  def edit
    @user_type = UserType.find(params[:id])
  end
  
  def update
    @user_type = UserType.find(params[:id])
    if @user_type.update(user_type_params)
      flash[:notice] = "ユーザータイプを更新しました"
      redirect_to user_types_path
    else
      flash[:notice] = "ユーザータイプを更新できませんでした"
      render "user_types/edit"
    end
  end
  
  def destroy
    @user_type = UserType.find(params[:id])
    if @user_type.destroy
      flash[:notice] = "ユーザータイプを削除"
      redirect_to user_types_path
    else
      flash[:notice] = "ユーザータイプを削除できませんでした"
      render "edit"
    end
  end
  
  private
    def user_type_params
        params.require(:user_type).permit(:user_type, :type_name, :price)
    end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/edit.html.erb
<div class="container edit">
<h2>編集</h2>

  <%= form_for @user_type, :url => {:action => "update" }, html: { method: :put } do |f| %>

  <div class="field user_type short">
    <%= f.label :タイプ %><br />
    <%= f.number_field :user_type, required: true, autofocus: true, :class => "form-control my-form", autocomplete: "user_type" %>
  </div>

  
  <div class="field type_name short">
    <%= f.label :タイプ名 %><br />
    <%= f.text_field :type_name, required: true, :class => "form-control my-form", autocomplete: "type_name" %>
  </div>

  <div class="field price short">
    <%= f.label :金額 %><br />
    <%= f.text_field :price, required: true, :class => "form-control my-form", autocomplete: "price" %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class:"btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back", :back %>
</dir>

app/views/user_types/index.html.erb
<div class="container">
    <h2 class="my-reserved-title">タイプ一覧</h2>
    
        <table class="table table-bordered table-schedule">
          <thead>
            <tr>
              <th scope="col">タイプ</th>
              <th scope="col">料金</th></th>
            </tr>
          </thead>
          <tbody>
            <% @user_types.each do |user_type| %>
               <tr>
                  <td><%= link_to user_type.type_name, edit_user_type_path(user_type.id) %></td>
                  <td><%= user_type.price %></td>
               </tr>
            <% end %>
          </tbody>
        </table>
</div>

app/views/user_types/new.html.erb
<div class="container new">
<h2>追加</h2>

  <%= form_for @user_type, :url => {:action => "create" }, html: { method: :post } do |f| %>

  <div class="field type_name short">
    <%= f.label :タイプ名 %><br />
    <%= f.text_field :type_name, required: true, :class => "form-control my-form", autocomplete: "type_name" %>
  </div>

  <div class="field price short">
    <%= f.label :金額 %><br />
    <%= f.text_field :price, required: true, :class => "form-control my-form", autocomplete: "price" %>
  </div>

  <div class="actions">
    <%= f.submit "追加", class:"btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back", :back %>
</dir>